---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/platform-stack/integration-test/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
