---
name: container-build-and-release-action
description: Build container if underlying Dockerfile changed.
branding:
  icon: anchor
  color: blue
inputs:
  dockerfile-location:
    description: The path to the Dockerfile that should be built and released.
    required: true
  registry:
    description: The registrys url to which the container image should be pushed to.
    required: true
  image-url:
    description: The entire url of the final image.
    required: true
  package-name:
    description: The package name of the built image in the registry to clean up old images
    required: true
  username:
    description: The username to log into the container registry.
    required: false
    default: ${{ github.actor }}
  password:
    description: The password to log into the container registry.
    required: true
  min-versions-to-keep:
    description: Minimum amount of built images to keep in the registry. Delete the rest.
    required: false
    default: -1 # Do not delete any.
  create-attest:
    description: Define whether the attestation file should be created and pushed or not (ghcr.io does not support attestation files for private repositories).
    required: false
    default: true
  github-token:
    description: The GitHub token used to make authenticated API requests.
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # We need the entire history to check if the Dockerfile has changed

    - name: Check if Dockerfile changed
      shell: bash
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '${{ inputs.dockerfile-location }}'; then
          echo "DOCKERFILE_CHANGED=true" >> ${GITHUB_ENV}
        else
          echo "DOCKERFILE_CHANGED=false" >> ${GITHUB_ENV}
        fi

    - name: Log in to the container registry
      if: env.DOCKERFILE_CHANGED == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      if: env.DOCKERFILE_CHANGED == 'true'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-url }}

    - name: Build and push Docker image
      if: env.DOCKERFILE_CHANGED == 'true'
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile-location }}
        push: true
        tags: |
          ${{ inputs.image-url }}:latest
          ${{ inputs.image-url }}:${{ github.sha }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Delete old container images
      if: env.DOCKERFILE_CHANGED == 'true'
      uses: actions/delete-package-versions@v5
      with:
        package-name: ${{ inputs.package-name }}
        package-type: container
        min-versions-to-keep: ${{ inputs.min-versions-to-keep }}

    - name: Generate artifact attestation
      if: ${{ inputs.create-attest }} == 'true'
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.image-url }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
        github-token: ${{ inputs.github-token }}

